### ISSUE TITLE
Data downloader: 404 Client Error: Not Found for url

### ISSUE THREAD

**Issue by 99991** [MaxBer04/DebiasDiffusion#1]
```
python public_data_downloader.py all --ouput_dir data
```

After fixing the [typo](https://github.com/MaxBer04/DebiasDiffusion/tree/main/tools#public_data_downloaderpy) (should be `output_dir` instead of `ouput_dir`), I get the following error:

```
$ python public_data_downloader.py all --output_dir data
Downloading full_package...
Traceback (most recent call last):
  File "/tmp/DebiasDiffusion/tools/public_data_downloader.py", line 112, in <module>
    main()
  File "/tmp/DebiasDiffusion/tools/public_data_downloader.py", line 102, in main
    download_full_package(args.output_dir)
  File "/tmp/DebiasDiffusion/tools/public_data_downloader.py", line 82, in download_full_package
    download_and_extract("full_package", output_dir)
  File "/tmp/DebiasDiffusion/tools/public_data_downloader.py", line 75, in download_and_extract
    download_file(url, local_filename)
  File "/tmp/DebiasDiffusion/tools/public_data_downloader.py", line 42, in download_file
    r.raise_for_status()
  File "/tmp/miniconda3/envs/nlp/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pub-e4d660081d944b389609a3d747f5cf10.r2.dev/full_package.tar.gz
```

The other packages trigger similar errors.

**Comment by MaxBer04** [comment]
Hello,
unfortunately there were some small bugs in the public data downloader still, since I always used the private one and forgot to check... However, i pushed a commit that fixed it. 
The compressed full package unfortunately is not in the bucket anymore somehow. I am currently re-uploading it however it may take some time since it  is over 1.5TB in total. 
The packages however can all be downloaded individually still. For example, to download the data for section 5.4.1 use:

```bash
python tools/public_data_downloader.py section_5.4.1 --output_dir data
```

I am sorry for the inconvenience and hope this helps.

**Comment by 99991** [comment]
Thank you for the quick fix! For testing, I downloaded a part of `section_5.4.1` and was able to extract it.
